name: Build and deploy
run-name: From ${{ github.event.head_commit.message }} by @${{ github.actor }}
on:
  push:
    tags:
      - "v*"
permissions:
  contents: read
  packages: write
jobs:
  docker_build:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Build docker image and push
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Test commands
        run: |
          uname -a
          ls -lh
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/svmpsp/svmpsp-dev
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
