name: Test action
run-name: Test run name
on: [push]
permissions:
  contents: read
jobs:
  simple_job:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Test commands
        run: |
          uname -a
          ls -lh
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: svmpsp-dev
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}