name: Test action
run-name: Test run name
on: workflow_dispatch
permissions:
  contents: read
  packages: write
jobs:
  simple_job:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Test commands
        run: |
          uname -a
          ls -lh
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/svmpsp/svmpsp-dev:latest